name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Verify version matches plugin header
      run: |
        PLUGIN_VERSION=$(grep "Version:" wp2static.php | sed 's/.*Version: *\([0-9.-]*\).*/\1/')
        TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
        
        echo "Plugin version: $PLUGIN_VERSION"
        echo "Tag version: $TAG_VERSION"
        
        if [ "$PLUGIN_VERSION" != "$TAG_VERSION" ]; then
          echo "Version mismatch! Plugin header shows $PLUGIN_VERSION but tag is $TAG_VERSION"
          exit 1
        fi
        
    - name: Create release directory
      run: |
        mkdir -p build/wp2static
        
    - name: Copy plugin files
      run: |
        rsync -av \
          --exclude='.git*' \
          --exclude='.github/' \
          --exclude='build/' \
          --exclude='composer.*' \
          --exclude='tests/' \
          --exclude='phpunit.*' \
          --exclude='*.md' \
          --exclude='node_modules/' \
          --exclude='.DS_Store' \
          --exclude='Thumbs.db' \
          ./ build/wp2static/
          
    - name: Create ZIP file
      run: |
        cd build
        zip -r ../wp2static-${{ steps.get_version.outputs.VERSION }}.zip wp2static/
        cd ..
        
    - name: Generate release notes
      id: release_notes
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        if [ -n "$PREVIOUS_TAG" ]; then
          CHANGES=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD)
        else
          CHANGES=$(git log --pretty=format:"- %s" HEAD)
        fi
        
        cat > release_notes.md << EOF
        # WP2Static v${{ steps.get_version.outputs.VERSION }}
        
        Static site generator for WordPress - Internal build.
        
        ## Changes in this release
        
        $CHANGES
        
        ## Installation
        
        1. Download the wp2static-${{ steps.get_version.outputs.VERSION }}.zip file
        2. Upload and activate in WordPress Admin → Plugins
        3. Configure in WP2Static → Options
        
        ## Requirements
        
        - WordPress 5.0+
        - PHP 7.4+
        - MySQL 5.6+ or MariaDB 10.0+
        
        ## Documentation
        
        For detailed documentation and usage instructions, visit the WordPress admin interface after installation.
        EOF
        
        echo "Release notes created"
        cat release_notes.md
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: WP2Static v${{ steps.get_version.outputs.VERSION }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./wp2static-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: wp2static-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip 