name: Release GitLab Private Add-on

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version in plugin files (from tag)
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF##*/}"
          VERSION="${TAG#v}"
          echo "Version from tag: $VERSION"
          sed -E -i "s/^(\\s*\\*\\s*Version:\\s*).*/\\1${VERSION}/" wp2static-addon-gitlab-private.php
          sed -E -i "s/(define\\(\\s*'WP2STATIC_GITLAB_PRIVATE_VERSION'\\s*,\\s*')[^']*('\\s*\\)\\s*;)/\\1${VERSION}\\2/" wp2static-addon-gitlab-private.php

      - name: Validate version set in plugin files
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF##*/}"
          VERSION="${TAG#v}"
          grep -E "^\s*\*\s*Version:\s*${VERSION}$" "wp2static-addon-gitlab-private.php" | cat
          grep -E "define\(\s*'WP2STATIC_GITLAB_PRIVATE_VERSION'\s*,\s*'${VERSION}'\s*\)" "wp2static-addon-gitlab-private.php" | cat

      - name: Build zip
        run: |
          mkdir -p dist
          zip -r9 dist/wp2static-addon-gitlab-private-${GITHUB_REF_NAME#v}.zip . \
            -x "**/.git/**" \
            -x "**/.github/**" \
            -x "**/.DS_Store" \
            -x "**/dist/**" \
            -x "**/scripts/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wp2static-addon-gitlab-private-${{ github.ref_name }}
          path: dist/*.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Verify version matches plugin header
      run: |
        PLUGIN_VERSION=$(grep "Version:" wp2static.php | sed 's/.*Version: *\([0-9.-]*\).*/\1/')
        TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
        
        echo "Plugin version: $PLUGIN_VERSION"
        echo "Tag version: $TAG_VERSION"
        
        if [ "$PLUGIN_VERSION" != "$TAG_VERSION" ]; then
          echo "Version mismatch! Plugin header shows $PLUGIN_VERSION but tag is $TAG_VERSION"
          exit 1
        fi
        
    - name: Create release directory
      run: |
        mkdir -p build/wp2static
        
    - name: Copy plugin files
      run: |
        rsync -av \
          --exclude='.git*' \
          --exclude='.github/' \
          --exclude='build/' \
          --exclude='composer.*' \
          --exclude='tests/' \
          --exclude='phpunit.*' \
          --exclude='*.md' \
          --exclude='node_modules/' \
          --exclude='.DS_Store' \
          --exclude='Thumbs.db' \
          ./ build/wp2static/
          
    - name: Create ZIP file
      run: |
        cd build
        zip -r ../wp2static-${{ steps.get_version.outputs.VERSION }}.zip wp2static/
        cd ..
        
    - name: Generate release notes
      id: release_notes
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        if [ -n "$PREVIOUS_TAG" ]; then
          CHANGES=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD)
        else
          CHANGES=$(git log --pretty=format:"- %s" HEAD)
        fi
        
        cat > release_notes.md << EOF
        # WP2Static v${{ steps.get_version.outputs.VERSION }}
        
        Static site generator for WordPress - Internal build.
        
        ## Changes in this release
        
        $CHANGES
        
        ## Installation
        
        1. Download the wp2static-${{ steps.get_version.outputs.VERSION }}.zip file
        2. Upload and activate in WordPress Admin → Plugins
        3. Configure in WP2Static → Options
        
        ## Requirements
        
        - WordPress 5.0+
        - PHP 7.4+
        - MySQL 5.6+ or MariaDB 10.0+
        
        ## Documentation
        
        For detailed documentation and usage instructions, visit the WordPress admin interface after installation.
        EOF
        
        echo "Release notes created"
        cat release_notes.md
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: WP2Static v${{ steps.get_version.outputs.VERSION }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./wp2static-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: wp2static-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip 